### ISSUE TITLE
Support adding config directly to appSettings.json

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#10]
I am just in the process of setting Smidge up (thanks for making this!)
I noticed this bit:

> Add a config file to your app root (not wwwroot) called smidge.json with this content:

Would it be possible for configuration to be added to the `appSettings.json` file instead? If Smidge uses IConfiguration this should just work?

**Comment by dazinator** [comment]
PR Submitted.

**Comment by Shazwazza** [comment]
Hi, thanks for all the feedback and prs! I'm just on holidays for a couple weeks but will get to all of this once I return
