### ISSUE TITLE
Breakpoints in sourcemaps only work on first file in a bundle. 

### ISSUE THREAD

**Issue by KevinJump** [Shazwazza/Smidge#106]
Looks like there is something odd with source mapping. 

_(examples below use the existing libs bundle already in the repo (contains jquery and knockout.js) - but you can reproduce with simpler files containing nearly empty methods.)_

In chrome (or edge) when you load the source maps for a bundle containing multiple files you can see all the files in the source map. 

![image](https://user-images.githubusercontent.com/431231/122027148-c48f3080-cdc2-11eb-8816-3ee1d54f94b7.png)

but you can only set breakpoints on the first file. 

![breakpoints](https://user-images.githubusercontent.com/431231/122027455-091acc00-cdc3-11eb-9e6b-3558f290e55b.gif)

the actuall source map file looks like it has references to both files, but its not mapping something somewhere.

**Comment by Shazwazza** [comment]
Source maps in smidge are all created and processed by Nuglify (separate project). Perhaps there's an upgrade/fix pending on that library, would need to check. Else if there's an issue in Smidge its how Smidge is telling Nuglify what to do. 

Did you replicate this issue directly from the Smidge source code/test web proj?

**Comment by KevinJump** [comment]
Yeah got the results in the web site I. This repo ☹️. I did do a quick update of nuglfy package in Smidge.Nuglfy project but it did seem to make a difference.

**Comment by KevinJump** [comment]
I've had a look around and i don't think you can get Nuglify to create a source map across multiple iterations. 

e.g the `SmidgeController `passes each file in a bundle into the preprocessor, and the pre-processor loads the contents and the Nuglify Processor "Uglifiys" the file and starts the source map process off. 
(https://github.com/Shazwazza/Smidge/blob/version-4/src/Smidge/Controllers/SmidgeController.cs#L115-L119)


but i can't see anything in Nuglify docs or code to support that this works :( 

it looks like Nuglify is expecting the JS code to be passed to it single pass, and then the source map is generated from that - so I think for source maps to work. the bundle method would need to go fetch all the file content and then pass that into the preprocssor once. 

there might be some possible to have some form of offset when you restart the source mapping - there is a `EndOutputRun` method in nugify that changes this(https://github.com/trullock/NUglify/blob/19ad92106d08b44216c2b81d10d160b193ca6e03/src/NUglify/JavaScript/V3SourceMap.cs#L144) but i suspect that isn't what it is actually doing.

**Comment by KevinJump** [comment]
i think i have a breakthrough.

Telling the sourcemap that you have added a new line to the file after each one in processed seems to help

e.g in nuglifyJs.cs

```
if (nuglifyJsCodeSettings.SourceMapType != SourceMapType.None && codeSettings.SymbolsMap != null)
{
  // tell the source map we have added a new line to the output (fixes offsets).
  codeSettings.SymbolsMap.NewLineInsertedInOutput();

  AddSourceMapAppenderToContextAsync(fileProcessContext.BundleContext, nuglifyJsCodeSettings.SourceMapType);
}

```

 **which branch is right for the PRs. (version 4?)**

**Comment by Shazwazza** [comment]
@KevinJump You sir are a legend :) 🎉 I will have a look at your PRs asap
