### ISSUE TITLE
using TimestampCacheBuster doesn't always return all the files.

### ISSUE THREAD

**Issue by KevinJump** [Shazwazza/Smidge#108]
Using : TimestampCacheBuster

When you bundle a lot of files (and this can take a little while with certain nuglify settings). the returned bundle may not contain all of the files that have been requests .

This is because the timestamp can change, during the processing (its to the nearest 5 seconds) and so you only get the files that where processed in a certain chunk.

this is hard to recreate without a lot of JS files, but it does happen if you have a lot of angular stuff etc. 

the timestamp cache buster just returns ticks so this changes - but it might not be the cache buster - there are a couple of places in the code where the `bundleRequest.CacheBuster.GetValue()` is called, but the request also has the parsedVesion number passed to it from the request. 

using the parsed version number will get the already cached version of the file.

**Comment by KevinJump** [comment]
Hi, 

Not sure about a PR for this one ? should the places that call CacheBuster.GetValue() all check for an existing version if they can, or do you think the TimestampCache buster needs updating ?

**Comment by Shazwazza** [comment]
@KevinJump  Interesting, and well spotted.  I was going to do a big writeup here but you inspired me to go refactor a bunch of things. Would love your review on this if you have time! The PR is here https://github.com/Shazwazza/Smidge/pull/112 and has some notes in it.

This should hopefully either resolve this issue or pave the way for resolving it. If this doesn't resolve the issue then we can look into another option like using a request cache with the timestamp cache buster so it's always a single timestamp per request.  Let me know what you think.

Thanks a ton 🙏
