### ISSUE TITLE
GetOrderedFileSet does not return an ordered file set

### ISSUE THREAD

**Issue by PhyxionNL** [Shazwazza/Smidge#119]
A HashSet does not preserve insertion order.

**Comment by Shazwazza** [comment]
ouch of course 🤦 🤦‍♂️ 

Thanks for the PR, looks great will get that merged.

**Comment by PhyxionNL** [comment]
Can you push a new version on NuGet with this change? Thanks.

**Comment by Shazwazza** [comment]
Have pushed a new version: https://www.nuget.org/packages/Smidge/4.0.0-beta.370
