### ISSUE TITLE
Concurrency issue

### ISSUE THREAD

**Issue by PhyxionNL** [Shazwazza/Smidge#122]
This is related to Dazinator, although it certainly could be handled better by Smidge. 
The problem occurs when multiple requests happen simultaneously while generating the same file(s):

```` 
InvalidOperationException: Cannot add item to the directory, as an item with the same name already exists.
Dazinator.Extensions.FileProviders.InMemory.Directory.FolderDirectoryItem.AddFile(IFileInfo file)
Dazinator.Extensions.FileProviders.InMemory.Directory.InMemoryDirectory.AddFile(string folderPath, IFileInfo file)
Smidge.InMemory.MemoryCacheFileSystem.WriteFileAsync(string filePath, string contents)
Smidge.InMemory.ConfiguredCacheFileSystem.WriteFileAsync(string filePath, string contents)
Smidge.FileProcessors.PreProcessManager.ProcessFileImpl(IWebFile file, BundleOptions bundleOptions, BundleContext bundleContext)
Smidge.FileProcessors.PreProcessManager.ProcessFile(IWebFile file, BundleOptions bundleOptions, BundleContext bundleContext)
Smidge.FileProcessors.PreProcessManager.ProcessAndCacheFileAsync(IWebFile file, BundleOptions bundleOptions, BundleContext bundleContext)
Smidge.SmidgeHelper.GenerateUrlsAsync(IEnumerable<IWebFile> files, WebFileType fileType, PreProcessPipeline pipeline, bool debug)
Smidge.SmidgeHelper.GenerateJsUrlsAsync(PreProcessPipeline pipeline, bool debug)
```` 
In PreProcessManager, it's already checked if a file exists:
https://github.com/Shazwazza/Smidge/blob/release/4.0.0/src/Smidge.Core/FileProcessors/PreProcessManager.cs#L75
But there's no locking mechanism there, which I think would be useful and it's also unlikely that processing is done constantly given that it's cached.
What do you think @Shazwazza?

**Comment by PhyxionNL** [comment]
Semi related: it would also be useful to make PreProcessManager an interface so you can use pass own implementation if necessary.

**Comment by Shazwazza** [comment]
Thanks again! all merged.

**Comment by PhyxionNL** [comment]
No problem, a nuget update would be appreciated :)

**Comment by Shazwazza** [comment]
Beta 376 is pushed https://www.nuget.org/packages/Smidge/4.0.0-beta.376
