### ISSUE TITLE
Using a dot in a bundle name causes an issue.

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#13]
It seems that there are some rules around bundle names that probably should be documented. It appears its not valid to use a "." in a bundle name, as this then causes an exception in `BundleModel`:

```
  public BundleModel(IUrlManager urlManager, IActionContextAccessor accessor)
            : base("bundle", urlManager, accessor)
        {
            if (!ParsedPath.Names.Any())
            {
                throw new InvalidOperationException("The bundle route value does not contain a bundle name");
            }

            _bundleName = ParsedPath.Names.Single();

        }
```

Which errors on `ParsedPath.Names.Single()`.

**Comment by Shazwazza** [comment]
For now I just validate the name and throw a useful exception, the URLs used by smidge are delimited with '.' which is why it cannot have it in the name (currently anyways)
