### ISSUE TITLE
Issues when deploying Umbraco v9.1.1  

### ISSUE THREAD

**Issue by teeto** [Shazwazza/Smidge#136]
I've had some issues after deploying an Umbraco v9.1.1 site due to Smidge minification.
First issue is due to path with querystring in manifest.json file. It works in v7 and v8 but not in v9.
Its explained here:
https://our.umbraco.com/forum/umbraco-9/107731-umbraco-9-cant-find-controller-for-my-block-list-editor-custom-view-after-deploy

Other issue is due to case sensitive paths as explained here:
https://our.umbraco.com/forum/umbraco-9//107740-umbraco-9-cant-register-controller-for-a-custom-dashboard-that-works-locally-but-fails-when-deploy

But after correcting both issues still it didnt load the controller so i had to deploy with this configuration:

`"RuntimeMinification": {
        "useInMemoryCache": true,
        "cacheBuster": "Timestamp"
      }`

With that it works, but i guess Smidge is disabled, isnt it?

**Comment by Shazwazza** [comment]
This just sounds like the old persistent cache is still in play. By changing those settings, it just means that the cache is not persistent. Instead, for production, just change the minification version `RuntimeMinification:version`, see https://github.com/umbraco/Umbraco-CMS/blob/v9/contrib/src/Umbraco.Web.UI/appsettings.template.json#L43

**Comment by psmoq** [comment]
The second issue which is described here still occurs. I.e. there is a problem with Iconic plugin. Following error appears in browser console:

![image](https://user-images.githubusercontent.com/19189902/175490395-6fd69c41-ab09-4e1d-8a18-963b04ae38aa.png)

the link leads to: https://code.angularjs.org/1.8.0/docs/error/$controller/ctrlreg?p0=Our.Iconic.Prevalues.Packages

The issue occurs even locally. After changing settings to:
`"RuntimeMinification": { "useInMemoryCache": true, "cacheBuster": "Timestamp" }` it starts to work as expected.

**Comment by Shazwazza** [comment]
@psmoq sounds like the same issue mentioned above, my advice was here https://github.com/Shazwazza/Smidge/issues/136#issuecomment-992981620
