### ISSUE TITLE
Smidge doesn't work when aspnetcore mvc is deployed to IIS 

### ISSUE THREAD

**Issue by bryanmillerph** [Shazwazza/Smidge#138]
Created a default aspnetcore mvc project in VS2022 (.NET6). 
Created the RequiresCss() and RequiresJs() on the Home/Index page

Web Deploy the project to IIS... any page with Smidge 

Adding "@addTagHelper *, Smidge" or "@inject Smidge.SmidgeHelper Smidge" directly on the cshtml layout page or via _ViewImports.cshtml will cause an HTTP500 on the IIS server and not load anything (no html document is served thru IIS, no error messages at all via serilog)

**Running aspnetcore mvc via kestrel works fine, smidge is bundling and minifying files as expected.**

Tested both IIS and Kestrel on Windows 10 (fully patched) and Windows 11 (fully patched)

**Comment by Shazwazza** [comment]
Is this still relevant? I haven't had any other reports about this at all. Is there a stack trace or anything else you can share?
