### ISSUE TITLE
Smidge removes spaces which result in a different css context

### ISSUE THREAD

**Issue by krebil** [Shazwazza/Smidge#139]
I'm using tailwind with the typography plugin they often use statements like this:
`.prose :where([class~=lead]):not(:where([class~=not-prose] *)) {
//some styling
}`

removing the space between `.prose` and ` :where`  makes it so that the children of the prose class is not affected by the where clause, effectively breaking most of the typography plugin

**Comment by jpinto3488** [comment]
We are having the same issue, is there any plan to get this fixed?
