### ISSUE TITLE
Better exception for when rendering a bundle that doesn't exist.

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#14]
In a view, if you 

```
@await SmidgeHelper.JsHereAsync("DoesntExist")
```

Where there is no such bundle, you gte an error like this:

![image](https://cloud.githubusercontent.com/assets/3176632/13222920/0583cee0-d97a-11e5-8c53-18534eab050b.png)

Should throw a more helpful / indicative error.

**Comment by Shazwazza** [comment]
Closing with PR: https://github.com/Shazwazza/Smidge/pull/26
