### ISSUE TITLE
Smidge 4x a way to specify an IFileProvider to use

### ISSUE THREAD

**Issue by mstoicescu** [Shazwazza/Smidge#140]
Hello, I'm looking for a way to make Smidge 4x to work after update from 3x. In prior version i used:

```
            services
                .AddSmidge(Configuration.GetSection("smidge"), fileProvider);
```
fileProvider (IFileProvider) is an EmbeddedFileProvider for production env. and PhysicalFileProvider for dev.

Is a possibility to achieve this in 4x version ?

**Comment by Shazwazza** [comment]
Sorry for the delay. Yes, you just replace the `ISmidgeFileProvider` in the container in ConfigureServices with your own implementation. ISmidgeFileProvider is just a marker interface that extends IFileProvider.
