### ISSUE TITLE
Scripts with type='text/javascript' throws warnings on HTML5 validators

### ISSUE THREAD

**Issue by AlphaDelta** [Shazwazza/Smidge#146]
Hi there,

At the moment Smidge currently prints its Javascript tags with `type='text/javascript'`.

I believe this happens right here https://github.com/Shazwazza/Smidge/blob/b0383c3b7e2b667402451dcff7055209ceabd428/src/Smidge/SmidgeHelper.cs#L81

This practice causes HTML5 validators to throw warnings about the 'type' attribute being unnecessary:
<img src="https://i.imgur.com/fKOs0Ph.png" />

Is it possible you could add a configuration option to remove the type attribute from the scripts Smidge outputs?

**Comment by Shazwazza** [comment]
Hi, sorry I meant to get this merged and released ages ago. There's a pending PR for this already IIRC https://github.com/Shazwazza/Smidge/pull/142

**Comment by Shazwazza** [comment]
PR is merged, these attributes will no longer be rendered in 4.0.4

**Comment by Shazwazza** [comment]
Also, you can just render the script/style tags yourself which is the recommended way and then you are in charge of the attributes:  https://github.com/Shazwazza/Smidge/wiki/Rendering
