### ISSUE TITLE
Question: Does Smidge allow you to specify additional HTML attributes for external sources?

### ISSUE THREAD

**Issue by NikRimington** [Shazwazza/Smidge#147]
Hey Shannon,

I've been having a look around the source code and I don't know if I'm missing it, but does Smidge allow for some JS files to be rendered out with extra attributes in the tags? For example, I want to use it to conditionally pull in Google Maps, but I want to have the `async` attribute on the rendered tag `<script async src="//maps.google.com/maps/api/js ....` 

However I can't see if this is possible?

Thanks

Nik

**Comment by Shazwazza** [comment]
How are you rendering your bundles? You can just add html attributes to your script tag.

https://github.com/Shazwazza/Smidge/wiki/Rendering

**Comment by Shazwazza** [comment]
This is possible with tag helpers, closing this issue.
