### ISSUE TITLE
Use cases and load ordering

### ISSUE THREAD

**Issue by craigs100** [Shazwazza/Smidge#155]
I may have been using Smidge wrong but I've spent most of the day chasing my tail so I thought I'd ask. I was upgrading an old Umbraco V7 site to V9.5. The old site's views included specific css and js files pertinent to that view using @sections (header and footer). I thought I could just use Smidge for that. Turns out I couldn't because I had no way to control the order of loading. If JQuery was included with the Base template, then anything that needed JQuery in the child templates errorred due to lack of JQuery because they were loaded before the scripts in the Base template and I had no control over this. 

```
  // Set up local JS
  SmidgeHelper.RequiresJs("~/scripts/slimmage.min.js");
  SmidgeHelper.RequiresJs("~/scripts/bootstrap.min.js");
  SmidgeHelper.RequiresJs("~/scripts/common.js");
```

Then in the Master template

```@await SmidgeHelper.JsHereAsync()```

Would it be possible to include an index number to control the loading order?
Or, have I just made some silly assumptions?  For now, I decided not to use Smidge on this project and have reverted to traditional, unbundled links to pre-minified files.

Cheers

**Comment by Shazwazza** [comment]
Smidge is not CDF. You cannot control when views are loaded, so you cannot do what you are proposing. If that were to work, it would mean the entire page hierarchy would need to be built up-front and wherever you are rendering your assets would need to know that all other views have been rendered (not possible). CDF worked around this by some serious hacks that only existed (but shouldn't have) in .NET Framework.

Smidge works with bundles. View based declarations can work but you will have to be sure you 100% know how the order of things is working but as you say, its not possible in many cases.

**Comment by Shazwazza** [comment]
See https://github.com/Shazwazza/Smidge/issues/145#issuecomment-1064653068
