### ISSUE TITLE
Smidge does not work well in mode debug=false

### ISSUE THREAD

**Issue by jmc18** [Shazwazza/Smidge#157]
Smidge does not work well in debug mode = false, when I set my site in debug false mode, the Umbraco backoffice of the plugins is not working.

Does anyone know what to add or update? I am using .net core 6 and it also happens in .net core 5

InvalidOperationException: Could not parse umbraco-backoffice-extensions-js.js as a valid smidge path

**Comment by Shazwazza** [comment]
Will close this issue since if this is still an issue it has to do with Umbraco's implementation.
