### ISSUE TITLE
Update Nuglify

### ISSUE THREAD

**Issue by Jeavon** [Shazwazza/Smidge#158]
Smidge is currently using 1.13.12 of Nuglify, could it be updated to the latest 1.20.2?

Loads of fixes in between, we just hit this one https://github.com/trullock/NUglify/pull/288 that was fixed in 1.17.6

**Comment by Shazwazza** [comment]
Yeah for sure, should be very simple to update if you can send a PR and then I can get it shipped?

**Comment by Jeavon** [comment]
Yep, will give it a try and verify our issue at least!

**Comment by Shazwazza** [comment]
Thanks. You can update your sln to the latest Nuglify too, I don't think Smidge has a hard limit on the version. I'm on holidays for a week so not sure I'll get a new release shipped before I return but I'll try - maybe today if a PR comes in soon.

**Comment by Jeavon** [comment]
https://github.com/Shazwazza/Smidge/pull/159 
Tested and indeed fixed by latest Nuglify, all tests passing also.
Interestingly our issue didn't occur when not using Nuglify (but Umbraco is using Nuglify so that's not an option).

**Comment by Jeavon** [comment]
Oh unrelated @Shazwazza but I had to manually create `test10.js` to get the project to run, must be missing from the repo
![image](https://user-images.githubusercontent.com/1829920/181836243-94aa063c-3a37-49e2-b5ee-13346cffd5d0.png)

**Comment by Shazwazza** [comment]
Awesome :) I've pushed those packages to Nuget now as 4.1.1, should be visible soon

**Comment by Shazwazza** [comment]
https://github.com/Shazwazza/Smidge/releases/tag/v4.1.1
