### ISSUE TITLE
How to get file watching to work?

### ISSUE THREAD

**Issue by milkmanmatty** [Shazwazza/Smidge#166]
I'm having trouble getting the file watch to do anything.
I've set the `FileWatchOptions.Enabled` to `true` and the CacheBusterType is set to `AppDomainLifetimeCacheBuster`. This display perfect on load: every file listed in Dev, and bundled & minified in Production. But if I make a change to one of the files when in Dev, nothing happens?? The Cachebusting doesn't update and the file doesn't reload, even on refresh.

My project is in .Net 6. Here's what I have got:

appsettings.json
```json
"smidge": {
    "dataFolder": "Smidge",
    "version": "1"
},
```

Program.cs
```csharp
builder.Services.AddSmidge(builder.Configuration.GetSection("smidge"))
                .Configure<SmidgeOptions>(options =>
                {
                    //Watch files for runtime reloading of changed files:
                    options.DefaultBundleOptions.DebugOptions.FileWatchOptions.Enabled = true;
                    options.DefaultBundleOptions.DebugOptions.SetCacheBusterType<AppDomainLifetimeCacheBuster>();

                    options.DefaultBundleOptions.ProductionOptions.SetCacheBusterType<AppDomainLifetimeCacheBuster>();
                });

// ...

app.UseSmidge(bundles =>
{
    bundles.Create("style",
                new CssFile("~/lib/bootstrap/dist/css/bootstrap.min.css"),
                new CssFile("~/css/**/*.css"))
           .WithEnvironmentOptions(bundles.DefaultBundleOptions);
});
```

_Layout.cshtml
```html
<head>
    <!-- ... -->
    <environment names="Development">
        <link rel="stylesheet" href="style" debug="true" />
    </environment>
    <environment names="Staging,Production">
        <link rel="stylesheet" href="style" />
    </environment>
</head>
```

Is there anything I need to add or do in order to get file watching to auto-update when in Development? Do I have to create my own CacheBuster?

I saw @Shazwazza say:
> Also note that if file watching is enabled, this also affects cache busting. If watching is enabled then the actual cache bust value is a combination of the ICacheBuster and the watched hash.

in https://github.com/Shazwazza/Smidge/issues/91#issuecomment-498931438. But I have not had this experience, how do I get it to actually update the `?b=` version string when the file changes while the app is running?

**Comment by CZEMacLeod** [comment]
@milkmanmatty Great that you've got a workaround, but the updating of the browser from the source file sounds like the BrowserLink feature in VS.

**Comment by milkmanmatty** [comment]
I also thought that at first, but I have it turned off. And when I turn on "Enable Browser Link" it actually changes the HTML.

Here's the HTML when first loaded:
![image](https://user-images.githubusercontent.com/9074205/197075296-89854aa1-9c5d-4231-b590-e045a604fe91.png)

Changing one of those CSS files won't make any change to that HTML (the `?b=` query string won't change for instance), but the css changes will still be visually shown in the browser (doing a `background: red` on body/html shows that pretty quickly lol). If I have Browser Link enabled the actual HTML changes when the file is saved locally - like so:

![image](https://user-images.githubusercontent.com/9074205/197075474-54031a7d-aabd-42e4-ae56-c625f9783f48.png)

In any case it looks to be working how I want it to work and that's, quite frankly, a Halloween miracle.
