### ISSUE TITLE
Request for .NET 6

### ISSUE THREAD

**Issue by qamarkhan84** [Shazwazza/Smidge#167]
i guess currently Smidge does not support .NET6.
Do we have any plan to upgrade this to .NET6.
![image](https://user-images.githubusercontent.com/98837075/198338283-251307fb-6f1a-445b-b760-7b3551c7cc41.png)

Many Thanks

**Comment by Shazwazza** [comment]
It does support .NET 6. Things that support .NET 5 work in .NET 6 too. That said, this could be multi-targeted to both, though it won't really make it run any better or differently because it won't be using any .NET 6 APIs that weren't available in .NET 5.

**Comment by qamarkhan84** [comment]
Agreed, Thank You

**Comment by Shazwazza** [comment]
I'll keep this open as a task for the future. Cross targeting can't hurt and would be more clear in the Nuget compat charts. Will also mark up for grabs.
