### ISSUE TITLE
Load balancing support for non pre-defined bundles

### ISSUE THREAD

**Issue by Shazwazza** [Shazwazza/Smidge#17]
Currently LB will really only work for pre-defined bundles. It could work for inline and non-named bundles too but i haven't got around to that just yet. There's really 2 ways to make this work:
- Swap the `IUrlManager` for a base64 Url Manager. This is currently what ClientDependency (https://github.com/Shazwazza/clientdependency) does (see: https://github.com/Shazwazza/ClientDependency/wiki/Composite-Files#url-types). This means that the URLs themselves contain the assets that need bundling/processing so it doesn't matter which server the request gets sent to. This works but the URLs get quite ugly/long and need to be split and they need to include an anti-forgery value.
- Create a Url/File mapping provider that can be swapped out with a centralized cache (i.e. a database, redis cache, etc...) 

Both options would mean that the pre-processing happens during the bundle request instead of during the html rendering request, so the logic for this would need to be abstracted out since currently that all just happens in the PreProcessManager.ProcessAndCacheFileAsync during the SmidgeHelper.GenerateUrlsAsync

**Comment by dazinator** [comment]
> Create a Url/File mapping provider that can be swapped out with a centralized cache (i.e. a database, redis cache, etc...)

Part of my PR allowed you to pass an `IFileProvider` to smidge, which it uses to get files based on paths. Microsoft provide some default implementations of IFileProvider:

- PhysicalFileProvider (maps request paths to some phsyical folder somewhere)
- EmbeddedFileProvider (maps request paths to files embedded within an assembly)
- CompositeFileProvider (aggregates a collection other file providers)

So in theory, you can currently pass smidge a `PhysicalFileProvider` pointing to a central network share somewhere.

But as for mapping paths to files held in a database, i'm guessing you'd have to implement an IFileProvider for that, and pass that to Smidge instead.

**Comment by Shazwazza** [comment]
Not going to pursue this feature, it is just recommended to use pre-defined bundles.
