### ISSUE TITLE
How to use with RequireJs (AMD)

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#18]
With `RequireJS` you have to construct a javascript object to configure it. 

You need to accomplish two things.

1. Add a "path" to the bundle file, and give this a name.
2. Specify which "modules" are in that bundle file, using a "bundles" section. 

Here is an example:

```
 @<script type="text/javascript">
        require.config({
            paths: {
                "primary": "/js/modules/bundlefile"
            },
          bundles: {
             'primary': ['MainMenuViewModel', 'SomeOtherModule', 'YetAnotherModule']
            }
        });
 </script>
```

You can then do this in javascript:

```js

 require(['MainMenuViewModel'], function (vm) {
           vm.SomeThing();
}

```

So based on that configuration, RequireJs uses the bundles config, to map the module name "MainMenuViewModel" to the javascript file: "primary", and it uses the paths section to determine that the "primary" script is loaded from `/js/modules/bundlefile.js`

I'm now trying to get this working with Smidge bundles.

`Smidge`, doesn't seem to produce a deterministic file name for the bundle file. This means you can't currently manually maintain this mapping, i.e what to put for question marks below?

```
 @<script type="text/javascript">
        require.config({
            paths: {
                "primary": "/App_Data/Bundler/Cache/ ?? ?? "
            },
            bundles: {
             'primary': ['MainMenuViewModel', 'SomeOtherModule', 'YetAnotherModule']
            }
        });
 </script>
```

Is there some way of getting the file name for the bundle file so that I can generate this config in a razor view.

**Comment by Shazwazza** [comment]
Does this help ? https://github.com/Shazwazza/Smidge#urls

**Comment by dazinator** [comment]
Ah sorry, i must have missed that somehow! Yeah that should do the trick. I'll close this once I have verified probs tomorrow

**Comment by dazinator** [comment]
Just looking at this now, it's a bit tricky. When doing a: `BundleHelper.GenerateJsUrlsAsync("MyBundleName"))` it returns a URL that looks like this:

`http://localhost:57929/sb/myfile.js.v1`

However I think `requireJs` needs to map it's module names to file ending in `.js` - so at the moment when I produce the following config it doesn't work:

```
require.config({
            paths: {
                "primary": "/sb/myfile.js.v1" // requirejs expects this to be without the .js and it appends it.
            },
            bundles: {
             'primary': ['MainMenuViewModel', 'SomeOtherModule', 'YetAnotherModule']
            }
        });

```

However if I just do this:

```
require.config({
            paths: {
                "primary": "/sb/myfile" 
            },
            bundles: {
             'primary': ['MainMenuViewModel', 'SomeOtherModule', 'YetAnotherModule']
            }
        });
```

Then require js is now going to request `/sb/myfile,js` instead of `/sb/myfile.js.v1`

I am wondering, would it be better to change the url smidge produces to have the v1 bit specified before the .js as then this could all work.. i.e `/sb/myfile.v1.js`
Or is there something I am missing?

**Comment by Shazwazza** [comment]
I can't remember if there was a specific reason for this :) It might have been so that the request is not detected as a static request. Definitely worth investigating, would be an easy change to see if it still works.

**Comment by dazinator** [comment]
Ah ok. Turns out you can stop `requirejs` from appending the '.js' to requests by specifying a query string value in the path mapping:

```

require.config({
            paths: {
                "primary": "/sb/myfile.js.v1?noext" 
            },
            bundles: {
             'primary': ['MainMenuViewModel', 'SomeOtherModule', 'YetAnotherModule']
            }
        });

```

This all seems to be working now without any changes to smidge necessary.

**Comment by Shazwazza** [comment]
Great! :)
