### ISSUE TITLE
Minification does not work - Umbraco 11.2.2 - Smidge 4.2.0

### ISSUE THREAD

**Issue by EvilDrPorkChop** [Shazwazza/Smidge#184]
Hi,

I've set up Smidge as per the Umbraco documentation but I seem to be running into an issue with minification specifically where CSS & JS files don't have any minification applied to them regardless of the Bundling options used.

Bundling & rendering work absolutely fine and I can use the smidge helper to render out the URLs etc. 
The cache is also building properly from what I can see.

I've tried changing all the settings within the Umbraco project and running Umbraco in production mode but I have got the same result.

My feeling is that there is something else unexpected going on with how Umbraco is implementing Smidge.

More than happy to provide any information that might be useful in narrowing down the cause of the bug.

Thanks

**Comment by Shazwazza** [comment]
Hi, if it's an issue with Smidge I'd be happy to look but if this is an issue or config thing with Umbraco you will need to ask on the Umbraco forum or GitHub with steps to replicate. If you can replicate on a vanilla web app with smidge without Umbraco I can have a look but the built in web app works so I don't think its that :)

**Comment by Shazwazza** [comment]
Closing this since no feedback.
