### ISSUE TITLE
Does it work on Linux

### ISSUE THREAD

**Issue by ccasalicchio** [Shazwazza/Smidge#186]
I've installed the site in Ubuntu 20.04 LTS running Umbraco v11 net 7.0
It doesn't seem to be working. Is there a specific configuration to set?

**Comment by Shazwazza** [comment]
There is nothing Windows specific with Smidge. It's installed with Umbraco which uses it quite heavily and there are a ton of Umbraco sites running on Linux.

**Comment by ccasalicchio** [comment]
So, no specific configuration, it should work just by using the defaults

`@inherits Umbraco.Cms.Web.Common.Views.UmbracoViewPage

<link rel="preconnect" href="https://fonts.googleapis.com">
<link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
<link href="https://fonts.googleapis.com/css?family=Open+Sans:300,400,600,700,800%7CShadows+Into+Light%7CPlayfair+Display:400" rel="stylesheet" type="text/css">
<link href="https://fonts.googleapis.com/css2?family=Roboto+Mono:wght@700&display=swap" rel="stylesheet">


<environment names="Staging,Production">
    <link href="css" rel="stylesheet">
</environment>

<environment names="Development">
    <link href="css" rel="stylesheet" media="screen" debug="true">
</environment>


`

**Comment by Shazwazza** [comment]
Is the tag helper imported? https://github.com/Shazwazza/Smidge#quick-start

**Comment by ccasalicchio** [comment]
Yes... I'm sure I'm missing something
![image](https://user-images.githubusercontent.com/2466879/231569578-138273eb-17ab-42d4-b967-5292ec18df52.png)

**Comment by ccasalicchio** [comment]
I got it to work using the View Base Declarations
![image](https://user-images.githubusercontent.com/2466879/231601306-d48ea7c0-f8b0-4f11-9107-6e1c73abeceb.png)

**Comment by ccasalicchio** [comment]
where do I configure it to minify the files? when I check, the browser (in production) the files are not minified.

**Comment by Shazwazza** [comment]
If view based declarations work then my assumption is that wherever you were making your bundles before was not executing?

**Comment by ccasalicchio** [comment]
Yes, I assume so, it's all good. I'm sure I was doing something wrong. Your library is awesome, congratulations!!!

**Comment by Shazwazza** [comment]
Thanks you, that is wonderful feedback :) 

Might be worth just creating a vanilla web app and install Smidge to wire everything up and see how it works without Umbraco, since Umbraco does install and configure Smidge separately - though it's implementation shouldn't interfere with the normal way to use Smidge. Will close for now. Thanks!
