### ISSUE TITLE
Minification Options

### ISSUE THREAD

**Issue by jackkjhsu** [Shazwazza/Smidge#187]
Hi,

Are there any options within Smidge for minification to mangle all variables, member names and remove all unnecessary white space characters? It seems that the default minification behaviour doesn't go far enough.

Thanks for your help.

**Comment by Shazwazza** [comment]
Hi, yes those options are based on the Nuglify options. 

The docs are missing this but they should live here https://github.com/Shazwazza/Smidge/wiki/installation#nuglify-minification-engine

The AddSmidgeNuglify takes an optional NuglifySettings parameter: https://github.com/Shazwazza/Smidge/blob/9510e0fc21b25196c5f83631a7ead16b0b5a90b0/src/Smidge.Nuglify/SmidgeNuglifyStartup.cs#L19

**Comment by jackkjhsu** [comment]
I guess the built-in JSMin doesn't expose any options? I'll play around with NUglify option.

Thanks Shannon.

**Comment by Shazwazza** [comment]
No JSMin is not 'smart' at all :) It's very fast though compared to Nuglify but also is limited with certain JS syntax and as JS evolves, unfortunately JSMin does not.
