### ISSUE TITLE
bundle css file path

### ISSUE THREAD

**Issue by pengweigang** [Shazwazza/Smidge#196]
I am using Umbraco, and bundle css file will be rendered like:
`<link href="/sb/sitebuilder-ltr-css-bundle.css.v1" media="screen" rel="stylesheet" />`
Is it possible to change "sb" in href to another text?

Thanks

**Comment by Shazwazza** [comment]
You can via SmidgeOptions configuration. This settings is found here https://github.com/Shazwazza/Smidge/blob/develop/src/Smidge.Core/CompositeFiles/UrlManagerOptions.cs

UrlManagerOptions are options defined on the SmidgeOptions: https://github.com/Shazwazza/Smidge/blob/develop/src/Smidge.Core/Options/SmidgeOptions.cs

Here's some docs on configuring SmidgeOptions https://github.com/Shazwazza/Smidge/wiki/installation

**Comment by pengweigang** [comment]
Thanks so much, it helps.
