### ISSUE TITLE
Script type and other attributes for JavaScript bundle

### ISSUE THREAD

**Issue by bjarnef** [Shazwazza/Smidge#203]
In a working project we have the following with ClientDependency:

```
Html.RequiresJs("~/dist/scripts/es6.min.js", new { @type = "module", @crossorigin = "" })
		.RequiresJs("~/dist/scripts/es5.min.js", new { @nomodule = "" })
		.RequiresJs("https://www.google.com/recaptcha/api.js?render=explicit", new { @async = "", @defer = "" });

@Html.RenderJsHere()
```

which render something like this:

```
<script src="[/DependencyHandler.axd?s=L2Rpc3Qvc2NyaXB0cy9lczYubWluLmpzOw&amp;t=Javascript&amp;cdv=1341141361](https://www.mydomain.com/DependencyHandler.axd?s=L2Rpc3Qvc2NyaXB0cy9lczYubWluLmpzOw&t=Javascript&cdv=1341141361)" type="module" crossorigin=""></script>
<script src="[/DependencyHandler.axd?s=L2Rpc3Qvc2NyaXB0cy9lczUubWluLmpzOw&amp;t=Javascript&amp;cdv=1341141361](https://www.mydomain.com/DependencyHandler.axd?s=L2Rpc3Qvc2NyaXB0cy9lczUubWluLmpzOw&t=Javascript&cdv=1341141361)" nomodule="" type="text/javascript"></script>
<script src="https://www.google.com/recaptcha/api.js?render=explicit" async="" defer="" type="text/javascript"></script> 
```

However when migrating the project from Umbraco 8 to Umbraco 13, I have replaced this with Smidge, but the scripts are not rendered correctly.
How do we handle this similar with Smidge?

Currently I have this:

```
SmidgeHelper
 	.RequiresJs("~/dist/scripts/es6.min.js") //, new { @type = "module", @crossorigin = "" })
 	.RequiresJs("~/dist/scripts/es5.min.js") //, new { @nomodule = "" })
 	.RequiresJs("https://www.google.com/recaptcha/api.js?render=explicit"); //, new { @async = "", @defer = "" });

@await SmidgeHelper.JsHereAsync()
```

which render something like this:
```
<script src="[/sc/8ba6800e.79124827.js.v1](https://mydomain.com/sc/8ba6800e.79124827.js.v1)"></script>
<script src="https://www.google.com/recaptcha/api.js?render=explicit"></script>
```

Looking at the documentation here https://github.com/Shazwazza/Smidge/wiki/Bundling-strategies I don't see any options to specify custom attributes like ClientDependency has.

E.g.

- `<script>` element with `type="module"` 
- `<script>` element with `async` or `defer` attribute
- `<script>` element with `crossorigin`, `referrerpolicy` or `integrity` attributes

I think `RequiresJs()` need an overload to pass in `object htmlAttributes` as in ClientDependency.

![image](https://github.com/Shazwazza/Smidge/assets/2919859/017820bc-2e6b-49e9-bd4b-eafe5d1cb6c5)

Also notice how the two JS assets with `@type = "module"` and `@nomodule = ""` in CDF was separated into two `<script>` elements.

**Comment by bjarnef** [comment]
@Shazwazza is there any equivalient to this in Smidge?

**Comment by Shazwazza** [comment]
Yes, just render with a script/link tag https://github.com/Shazwazza/Smidge/wiki/Rendering
