### ISSUE TITLE
Smidge interfering with Razor Class Library Umbraco plugin javascript controller ?

### ISSUE THREAD

**Issue by binraider** [Shazwazza/Smidge#204]
I am developing a plugin using a Razor Class Library for Umbraco 13.
In development mode it works fine but when published to production the plugin javascript controller 
(/App_Plugins/DoctypeUtility/doctypeutility.controller.js)  is not found.

Looking in the logs reveals that 

```
System.IO.FileNotFoundException: No such file exists /App_Plugins/DoctypeUtility/doctypeutility.controller.js?d=2024-03-27 (mapped from /App_Plugins/DoctypeUtility/doctypeutility.controller.js?d=2024-03-27)
File name: '/App_Plugins/DoctypeUtility/doctypeutility.controller.js?d=2024-03-27'
   at Smidge.SmidgeFileSystem.GetRequiredFileInfo(IWebFile webfile)
   at Smidge.FileProcessors.PreProcessManager.<>c__DisplayClass8_0.<ProcessFileImpl>b__0()
   at System.Lazy`1.ViaFactory(LazyThreadSafetyMode mode)
   at System.Lazy`1.CreateValue()

```
At the same time if i put the published url with the full path e.g. "umbraco13a4.local/App_Plugins/DoctypeUtility/doctypeutility.controller.js?d=2024-03-27" into the browser the javascript file is there. 
Not only that its also there on disk. 

Is Smidge interfering with the plugin angular somehow? The plugin html file shows fine (at least non-interactive stuff does) and the c# code in the plugin also works. 

In terms of development 

- i have a local nuget repository and compile the RCL seperately from the Umbraco host project and install/update the package as if it were a remote package.
- The package.manifest is added using the IManifestFilter / Composer method
- Smidge is not being used other than implicitly by Umbraco
- a vanilla 13.2 version of Umbraco with no umbraco packages nor other nuget packages apart from Azure blob

**Comment by binraider** [comment]
[Paravel.DoctypeUtility.1.0.9.zip](https://github.com/Shazwazza/Smidge/files/14884207/Paravel.DoctypeUtility.1.0.9.zip)

Here is the (local) nuget package - the settings are  like so:

```
"DTUSettings": {
  "AuthToken": "6c1fddb5-003c-4059-bbe4-8be016e12e5f",
  "Sites": [
    {
      "Local": false,
      "Name": "Local Published",
      "Url": "http://umbraco13a4.local"
    },
    {
      "Local": true,
      "Name": "Debug",
      "Url": "http://localhost:44324"
    }
  ]
},

```
If you were calling it from postman (https://umbraco13a4.local/umbraco/api/DoctypeUtility/getdoctypesauth) you would use the AuthToken value in a Bearer Token like so:

![image](https://github.com/Shazwazza/Smidge/assets/38069359/11db3fea-ed7c-4abe-9f53-3e22d4c4d756)

**Comment by binraider** [comment]
...

**Comment by konius** [comment]
We're experiencing a similar issue with Media Protect and Member Export on Azure, but not locally. 

Seeing this in the log viewer, but can access the file via the URL directly.

```
System.IO.FileNotFoundException: No such file exists /app_plugins/memberexport/css/memberexport.css (mapped from /app_plugins/memberexport/css/memberexport.css)
File name: '/app_plugins/memberexport/css/memberexport.css'
   at Smidge.SmidgeFileSystem.GetRequiredFileInfo(IWebFile webfile)
   at Smidge.FileProcessors.PreProcessManager.<>c__DisplayClass8_0.<ProcessFileImpl>b__0()
```
