### ISSUE TITLE
Better exception for when bundling a file that doesn't exist

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#25]
If you try to create a bundle, but one of the file's cannot be found:

![image](https://cloud.githubusercontent.com/assets/3176632/14018308/05360fee-f1c5-11e5-85aa-1f82a988e097.png)

The exception doesn't tell you the problematic file path however, this would be better if it told you which path can not be found.

**Comment by dazinator** [comment]
I'll submit a PR for this if that's ok

**Comment by Shazwazza** [comment]
That'd be ace! More PRs the better :) I'll be back after Easter to get a new release out

**Comment by Shazwazza** [comment]
Closing with PR: https://github.com/Shazwazza/Smidge/pull/26
