### ISSUE TITLE
Consider adding a gitattributes file for line endings

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#27]
Here is a typical one for Visual Studio development:

https://github.com/Danimoth/gitattributes/blob/master/VisualStudio.gitattributes

I think you just add it to the root of the repo. I am guessing that without this file, different people commiting may have different line ending settings resulting in the horrible diffs.

I might be wrong in all this, feel free to close this if you deem it too much hassle.

**Comment by Shazwazza** [comment]
Will close this but assuming this should be solvable with .editorconfig?
