### ISSUE TITLE
Source map declarations, and comments

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#29]
When smidge processes a file, the file may contain a source map declaration:

```
//# sourceMappingURL=jquery.min.map
```

These are useful for debugging purposes, when you typically wouldn't have smidge enabled.

However when smidge is enabled, its going to leave that sourcemap declaration in the output bundle, and the browser will attempt to load the sourcemap relative to the bundle file location - and as we don't attempt to move sourcemap files to the bundle file location then the browser wont finr the sourcemap and you see an error in the console.

The original sourcemap is kind of useless anyway after smidge has processed the file because as smidge can perform pre-procesisng, the new source code will no longer match the original sourcemap - so the sourcemap is kind of redundant when smidge is on.

For this reason I think a couple of new pre-processors might be a good idea:
1. RemoveSourceMapsPreProcessor - this will do what it's name suggests by removing sourcemap declarations from the script contents.
2. RemoveCommentsPreProcessor - I think this preprocessor is a nicety to avoid issues like #23 and as sourcemap declarations are a form of comment block, this would potentially take care of the sourcempas issue as well.

**Comment by dazinator** [comment]
Just thought I'd give an update on this as I have done some work on this recently (in NetPack branch), and I have managed to come up with a pure C# implementation for combining javascript files, which supports source maps.

The way it works is that for each file to be added to the bundle:

1. Check if the last non empty line is a sourceMappingUrl declaration - if it is, write an empty line to the bundle file, but parse the declaration so you can see the path to the source map file that it points to.

2. After all the files have been written to the stream, but prior to returning it, if you encountered any source mapping url declarations, use them to build a new type of source map called an "IndexMap" - which is basically just a source map that points to other source maps, specifically created to cater for post processing - [described here](https://docs.google.com/document/d/1U1RGAehQwRypUTovF1KRlpiOFze0b-_2gc6fAH0KY0k/edit?pref=2&pli=1) and write that out to a file to that it can be resolved on some path - i.e `/bundle.js.map`. Lastly, append a sourceMappingUrl directive to the end of the bundle / combined file that points to that index map.

I'm going to add support for CSS source maps next and see how that goes - in theory its pretty much identical just slightly different syntax for the source mapping url directive.

**Comment by Shazwazza** [comment]
nice! I'll have a peek when I find some of this so called 'time' :P I've also refactored a bunch of stuff for the pre-processors so they will work on a non-request thread by having a base url defined (which can be explicitly or automatically set), haven't got that all working yet but once that is in place, then having file watching + environment specific (debug vs non debug) pipelines available.

**Comment by merly-cortez** [comment]
Hi, 
Is this issue still open or the mentioned pre processors above have been implemented? I would like to understand how to deal with sourcemaps when using smidge. Thank you.

**Comment by Shazwazza** [comment]
@merly-cortez if you want to use source maps you will need to use [Smidge.Nuglify](https://www.nuget.org/packages/Smidge.Nuglify) as mentioned in the [readme](https://github.com/Shazwazza/Smidge)

This issue is quite old and IIRC the issues mentioned here have been resolved.
