### ISSUE TITLE
CssRewriteUrlTransform

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#33]
I have just became aware of this class from the System.Web.Optimization library: https://msdn.microsoft.com/en-us/library/system.web.optimization.cssrewriteurltransform(v=vs.110).aspx

Basically, when bundling using `system.web.optimization` you can allow it to re-write any relative url's in the CSS file so that still works after its moved to the bundle file location. This is useful for CSS files that reference local assets like FA does with its fonts files..

Might be an idea to try and implement this kind of thing for Smidge as a feature - assuming it doesn't do that already?

**Comment by Shazwazza** [comment]
we do this already: https://github.com/Shazwazza/Smidge/blob/master/src/Smidge/FileProcessors/CssUrlProcessor.cs

**Comment by dazinator** [comment]
Ah just realised that haha.. my bad! :)

**Comment by Shazwazza** [comment]
:smile:
