### ISSUE TITLE
netstandard

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#36]
As `Smidge` is a library, it should probably target `netstandard` (Atleast that's my understanding, Applications target netcoreapp).

I'll add netstandard and submit a PR for review.

**Comment by Shazwazza** [comment]
I think i may have tried that, can't remember but happy to see if it works. They've really made a giant confused mess of all of this.

**Comment by Shazwazza** [comment]
gonna close this now, just in the middle of upgrading to 1.0.0 and pretty sure netstandard is dead? https://github.com/NuGet/Home/issues/2524

**Comment by dazinator** [comment]
To my knowledge `netstandard` is not dead :-)

The issue you linked relates to `netstandardapp` which sounds like an incorrect TFM - `netcoreapp` is used for applications / exe's that target net core framework. `netstandard` is used for libraries that run on net core framework.

**Comment by Shazwazza** [comment]
haha, ok damn, thought it was a quick and easy find. I'll see what i can do about the lib project with 1.0.0 out.

**Comment by dazinator** [comment]
haha no probs. Some more info here about netcoreapp and netstandard libraries: https://github.com/dotnet/corefx/blob/master/Documentation/architecture/net-core-applications.md

**Comment by dazinator** [comment]
P.S this stuff is hella confusing.Please take everything I say (except that last sentence) with a pinch of salt.

**Comment by Shazwazza** [comment]
Ok, that's all fixed up now, the lib proj is now using `"NETStandard.Library": "1.6.0"`

**Comment by dazinator** [comment]
Awesome.. can I be a pain though...is there anyway you can make it `NETStanadard.Library 1.5` instead? As that is compatible with desktop .NET 4.6.2 (https://docs.microsoft.com/en-us/dotnet/articles/standard/library)

.NET 4.6.2 is the minimum version of desktop .net supported by ASP.NET MVC 6 (as of RC2) so its feasible that people, like myself, will be targeting desktop .NET 4.6.2 in their applications, so would be good if Smidge could be compatible..

**Comment by Shazwazza** [comment]
Hrm, trying to do that causes some issues, I do have net461 targeted as well so it should work on anything 4.6.1+ on desktop (afaik)

**Comment by dazinator** [comment]
ah ok good point! i'll give this a go at some point. Cheers

**Comment by Shazwazza** [comment]
I don't think i can reference a 1.5 dependency since 1.5 doesn't have a full release: https://www.nuget.org/packages/NETStandard.Library only 1.6 is available. But it does multi-target to 4.6.1 so it 'should' work :)

**Comment by dazinator** [comment]
Hmm.. So I tried installing it into a .net 452 project but it doesn't looks like the multi targeting hasn't worked:

![image](https://cloud.githubusercontent.com/assets/3176632/16493871/17e893f2-3edf-11e6-8535-3680ddc0eb26.png)

Ofcourse I can upgrade my solution to net 453, but just concerning given that people can use .net452 with asp.net MVC RTM.

**Comment by Shazwazza** [comment]
ah, it's multi-targeted for 4.6.1 or 4.6.2 (cant remember), i'll try to change to 4.5.2 and see if it compiles when i get a minute

**Comment by Shazwazza** [comment]
I've re-targeted to 4.5.2 and can verify that it installs via nuget just fine ... but now is the interesting part, since this was built against ASP.Net Core, I now need to find a way to boot and use Smidge :)

**Comment by Shazwazza** [comment]
Ah, I'm just being an idiot :P I installed Smidge on a non ASP.Net Core site on 4.5.2 - which would actually work if it could be wired up. I've just tested installing it on an ASP.Net Core site targeting .Net Framework 4.5.2 and it works

**Comment by dazinator** [comment]
Perfect thanks for this - i'll also give it a go!

**Comment by dazinator** [comment]
Yep worked great for me, cheers
