### ISSUE TITLE
JavascriptServices

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#39]
Just stumbled accross the [JavascriptServices](https://github.com/aspnet/JavaScriptServices/blob/dev/README.md) package - have you seen that yet? I think it looks quite interesting in that it would allow us to create pre-processors that leverage npm tooling. There are minifiers / transpilers available on npm platform that support things like sourcemaps as well as typescript files - so might open up some possibilities.

**Comment by Shazwazza** [comment]
Used to be called: using Microsoft.AspNetCore.NodeServices; but they've prob changed the name since

**Comment by Shazwazza** [comment]
If you look through the source for NodeServices, you'll find some examples, it's actually super easy. See: https://github.com/Shazwazza/Smidge/blob/master/src/Smidge/FileProcessors/NodeMinifier.cs and then have a look at the js test files.

**Comment by dazinator** [comment]
Recently saw Steve Sanderson's presentation (on the last asp.net community standup) and the WebPack middleware stuff looks very interesting - with hot module replacement etc. 

I have absolutely no idea how HMR works,

The problem with webpack, and the advantage that smidge has right now as I see it, is that webpack runs in an external process (nodejs) and the middleware is basically a fancy command line. Therefore the webpack stuff can't use your applications `IFileProvider` - so it can only see files that are placed on the physical file system. This is a problem for me, because I rely on the `IFileProvider` concept quite heavily. My application can have extensions installed at runtime, that install with them, embedded assets (.js files etc) and the beauty of Smidge, is that it can see all of these assets (Physical and Embedded), because it sits on top of the `IFileProvider` so can resolve any of those files for pre-processing and bundling. Some of them could be held in azure blob storage for all smidge cares.

So because of this, I can't use the new WebPack stuff right now, but it made me think, could or should Smidge evolve to try and give some of these workflow type of features?

One big feature would be, when in "Dev" mode (i.e no bundling takes place) - to automatically compile files again when they are edited. This would imply some sort of watcher, or perhaps a way to be notified from the `IFileProvider` when a File is changed? 

What do you think?

**Comment by Shazwazza** [comment]
Will need to think much more about this, I haven't had much time to absorb what you've said above :) I also saw the standup and this stuff seems cool - I have basically no experience with WebPack but not really sure it needs to be leveraged. A few folks in my office have created some browser sync modules which I assume is exactly HMR but with a different name so i can ask them.

In the meantime, I had a bit of fun and added a new NodeJs Uglify pre-processor - which in this rev is the default JS minifier: 4d841613bcc72e11edc05ea4e07969ec901cab88

Works pretty well but will assume that the processing/cpu time is higher than the jsmin stuff but is probably ok. Be cool to get .less, typescript and sass pre-processors setup which i assume will be pretty straight forward given how easy it was to invoke uglify.

**Comment by Shazwazza** [comment]
This is already in there now, i'll need to make a separate nuget package for this as I don't want to ship with it in by default. I've put benchmarks together here though so you can see why JsMin is preferred as a runtime minifier: https://github.com/Shazwazza/Smidge/wiki/Custom-pre-processing#minification-benchmarks

Now just need to allow passing in a custom Json string to configure the Js Uglify script

**Comment by Shazwazza** [comment]
Closing this as it's not a requirement and javascript services has been retired
