### ISSUE TITLE
Won't work with .NET Core RC1

### ISSUE THREAD

**Issue by cindro** [Shazwazza/Smidge#4]
Hi,

First of all, thank you for this amazing tool, its unfortunate that the old optimization method was left out of ASP.NET 5.

I have tried everything and can't get this package to work with .NET Core RC1 and MVC 6.

I in fact recreated your sample app and it still doesn't work with my dnx, any ideas?

**Comment by Shazwazza** [comment]
This isn't built against RC1 yet (docs state: _Currently supporting DNX 4.5.1 & DNXCore 5.0, built against beta8_): which is most likely the issue.

I'll update the project today with a new build and I have some tag helper features to add as well. I'll let you know when that's all done!

Thanks,Shannon

**Comment by cindro** [comment]
Oh ok, thank you for that. I look forward to the updated version.

**Comment by Shazwazza** [comment]
Hi, I've released the new version: 

https://github.com/Shazwazza/Smidge/releases/tag/1.0.0-rc1

Also be sure to read the docs, I've updated the documentation with some new features and also how debugging works.

**Comment by cindro** [comment]
Yep, thank you. It works now, sweeeeet
