### ISSUE TITLE
Rtm?

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#40]
Now that RTM has been released, probably worth updating!

**Comment by Shazwazza** [comment]
Yup! Just trying to get these last things done and I'll release 1.0.0 
https://github.com/Shazwazza/Smidge/milestones/v1.0.0

almost done the minified address thing

**Comment by Shazwazza** [comment]
https://www.nuget.org/packages/Smidge/1.0.0 :)

**Comment by dazinator** [comment]
Works a treat ;)
