### ISSUE TITLE
[Idea] - File watching, and re-bundling

### ISSUE THREAD

**Issue by dazinator** [Shazwazza/Smidge#41]
Have an idea.

`IFileProvider`'s allow you to "watch" given files for changes by registering a delegate / callback.

Perhaps we could enhance smidge to also watch the source / input files using that mechanism, and then when a change is detected, re-execute the pipeline?

I'll experiment in a branch

**Comment by dazinator** [comment]
Decided to try and flesh this out in my own library to see how far I get haha: https://github.com/dazinator/NetPack/blob/master/README.md

**Comment by Shazwazza** [comment]
Nice! :) Will have a browse when I've got some time on my hands and check out your PR with your comments - need some more time in the day !
