### ISSUE TITLE
Feature Request: Add option for in-memory bundle cache

### ISSUE THREAD

**Issue by josh-sachs** [Shazwazza/Smidge#46]
Would it be straight forward to create a configuration option that uses in-memory caching of the bundles instead of disk? 

I would prefer to incur the overhead re-generating the bundles when the application restarts as opposed to having to delete the cache folder or increment the version every deployment.   For applications hosted in an Azure always on scenario a restart generally only occurs when a new deployment is performed anyway.

**Comment by kudoz83** [comment]
I think this could be a SmidgeOption

`UseMemoryCache = true`

If this is provided, the IConfigurationSection and smidge.config is no longer required.  Just assume

```
{
   dataFolder: null,
   version: DateTime.UtcNow.Ticks.ToString()
}
```

**Comment by Shazwazza** [comment]
Yup, I can do this too - as noted in my previous comment about v2 https://github.com/Shazwazza/Smidge/issues/48

**Comment by Shazwazza** [comment]
Don't meant to keep pushing this to other versions but need to get some patch fixes out. I really want to get this done but will move to the next major version. I'll create something like a `IFileCacheProvider` which can be configured on startup, perhaps with some nice extension methods to easily just do something like `UseMemoryCache`.
