### ISSUE TITLE
Feature Request:  Add Options to Control Etag and Cache-Control headers.

### ISSUE THREAD

**Issue by kudoz83** [Shazwazza/Smidge#48]
The following options would be beneficial to those of us more concerned with the "Bundling Workflow" vs all the optimizations.  I imagine it would be trivial to add to the SmidgeOptions...

```
EnableEtag = false
CacheControlMaxAge = integer (0 == disabled).
```

The idea is I can work on all my build processes to auto-version and whatnot once I've got an MVP, instead of needing to solve for cache-busting/versioning while my app is still being developed.   I know "debug==true" is an option, but we currently stage against the bundled/minified resources and having to worry about forgetting to increment versions / clear cache and all of that during this process is overhead I'd like to push off post MVP.

**Comment by Shazwazza** [comment]
Yup can look into this, I'm in the middle of working on a v2 which will also help solve the debug==true stuff. In v2 you can have the pipelines all execute for any files types/bundles and have different options for different environments (i.e. debug, production). This way you can have all the minification still being performed in debug but not bundled (for example). I can add more options like this too.

**Comment by Shazwazza** [comment]
This is implemented now, for example this is how you would do it: https://github.com/Shazwazza/Smidge/commit/c89986fceacd4bee3476311d1d2dc30bf0c3292a#diff-30fbbf9f392f23bc5a5b6d71102e6bd4R99

This will be part of Smidge 2.0 (just need to find time to finish it now)
