### ISSUE TITLE
Named bundles exception when no resources found via pattern matching/search.

### ISSUE THREAD

**Issue by josh-sachs** [Shazwazza/Smidge#49]
If you create a named bundle, and the bundle that acquires it's resources via pattern matching / search (e.g. all css files in a directory) the bundle will throw the following exception if at least 1 matching file doesn't exist in the search directory. 

`Cannot return null from an action method with a return type of 'Microsoft.AspNetCore.Mvc.FileResult'`

What should happen is that RenderJssHereAsync and RenderCssHereAsync should simply not render tags for named bundles that don't contain any assets... If someone requests a bundle that is empty, smidge should just return 404 not found or an empty 200 response - up to you, not sure what is appropriate.

Note, this only occurs when debug == false and the pipeline is executed. 

I think you could try to reproduce with... 

`bundles.Create("styles", new CssFile[0]));`

**Comment by Shazwazza** [comment]
Have pushed a fix for this. The script/link element will still be rendered because at the time of generating URLs Smidge doesn't perform any IO tasks so it doesn't know at that point what is in the bundle. I've updated the server to return a 404 though when there are no file found for a bundle.
