### ISSUE TITLE
Calling a wrong style/script address

### ISSUE THREAD

**Issue by cindro** [Shazwazza/Smidge#6]
I have below code in startup.cs
bundles.Create("style", new CssFile("/theme/design.css")); (works fine)

Now when I call style from the root page (e.g: /) it works and calls this css file: /sb/style.css.v1

But when I call any other page such as /home/about, Smidge gets the css address wrong and calls: /home/sb/style.css.v1

/auth/login will result in Smidge looking for /auth/sb/style.css.v1 instead of just /sb/style.css.v1

Same with JS

**Comment by Shazwazza** [comment]
Doh! Of course, very silly of me to not deal with that (pretty fundamental :P )

I've just committed the some fixes that should fix up this issue. I'm on holidays for a couple of weeks so won't make a new release until I'm back however if you clone the site you can just run the /build.ps1 script and it will build a new version. It will ask for a version number (i.e. 1.0.0) and a pre-release version (you need to make sure you enter the hyphen, like -RC1A)

**Comment by cindro** [comment]
Enjoy your holiday.

Thanks for the update, managed to get it to work, AWESOME package.

**Comment by Shazwazza** [comment]
I created an RC2 release with this fix: https://www.nuget.org/packages/Smidge/1.0.0-rc2

**Comment by cindro** [comment]
Thank you for doing that, this is really a great tool, specially for those of us who loved Microsoft.AspNet.Web.Optimization, keep it up sir.
