### ISSUE TITLE
Cannot retrieve bundle URLs within a controller (not cshtml)

### ISSUE THREAD

**Issue by josh-sachs** [Shazwazza/Smidge#60]
I can't see a way to obtain the url of a named bundled resource in a web controller.

I have an API endpoint that instructs a webworker on where to download the current version of the bundled application.

**Comment by Shazwazza** [comment]
Can you provide the example code you are using and the version of Smidge you are using?

**Comment by kudoz83** [comment]
Smidge 2.0.0-alpha

The documentation says :
`Task<IEnumerable<string>> SmidgeHelper.GenerateJsUrlsAsync()
Task<IEnumerable<string>> SmidgeHelper.GenerateCssUrlsAsync()`

I inject SmidgeHelper into MVC Controller...

`[FromServices]SmidgeHelper smidgeHelper`

`var jsUrls = await smidgeHelper.GenerateJsUrlsAsync();`

jsUrls is empty.

a sample of the bundles getting created...

`builder.UseSmidge(bundles => {
bundles.Create("connect-dst",
					new JavaScriptFile("~/dst/release.sfx.min.js"))
					.WithEnvironmentOptions(BundleEnvironmentOptions.Create()
						.ForDebug(options => options
							.EnableCompositeProcessing()
							.EnableFileWatcher()
							.SetCacheBusterType<AppDomainLifetimeCacheBuster>()
							.CacheControlOptions(enableEtag: true, cacheControlMaxAge: 0))
						.ForProduction(options => options
							.EnableCompositeProcessing()
							.EnableFileWatcher()
							.SetCacheBusterType<AppDomainLifetimeCacheBuster>()
							.CacheControlOptions(enableEtag: true, cacheControlMaxAge: 31556926))
						.Build()					
					);
});`

**Comment by Shazwazza** [comment]
Sorry i realize this is extremely old but perhaps this was an issue with the pre-release. This has been working for some time and in the Smidge web tests itself. There's an example of this too in the umbraco project https://github.com/umbraco/Umbraco-CMS/blob/netcore/netcore/src/Umbraco.Web.Common/RuntimeMinification/SmidgeRuntimeMinifier.cs#L87.
