### ISSUE TITLE
Decouple MVC dependency

### ISSUE THREAD

**Issue by stanac** [Shazwazza/Smidge#65]
It would be nice to have Smidge without MVC dependency. So we could have e.g. `Smidge.Core` and `Smidge.Mvc`. This way apps that don't depend on MVC in the first place doesn't have to reference it.

**Comment by Shazwazza** [comment]
sounds like a good plan, just need to find some time otherwise if you've got time for a PR, that would amazing!

**Comment by Shazwazza** [comment]
This has been done in branch ` task/smidge-core-proj` but need to wait until https://github.com/Shazwazza/Smidge/pull/112 is merged.
