### ISSUE TITLE
create a .vue file bundler

### ISSUE THREAD

**Issue by mika76** [Shazwazza/Smidge#66]
Basically a vue-loader for .net core like https://github.com/vuejs/vue-loader would be great.

**Comment by Shazwazza** [comment]
Just on holidays at the moment so will reply in a few weeks

**Comment by Diaskhan** [comment]
Is there some update on that ?

**Comment by Shazwazza** [comment]
Sorry unfortunately no. I don't really think it's something that should be implemented. Runtime bundling should really be reserved for smaller processes. Things like vue should really be pre-processed/compiled before shipping.

**Comment by Shazwazza** [comment]
That said, if anyone wants to give it a try, i'd be interested to see where it goes and if its possible but I suspect that it would be painfully slow. Since vue is a JS framework, it would probably mean booting up the AspNet JavaScriptServices, running a compilation, etc...

**Comment by mika76** [comment]
The thing is, if you have a process like webpack or any other packages to do vue then you would not need this library at all since all javascript and css would already be bundled and minified.

It's just frustrating that all bundlers are pure javascript and you need Node as a dependency...

**Comment by Diaskhan** [comment]
https://github.com/vuejs/vue-loader
vue loader is third party extension for webpack! 
Vue files is not js files! its custom file that webpack could trasnpile  with vue-loader!

Transpile and minification is different things !

**Comment by mika76** [comment]
@Diaskhan I understand that, but the description for this library is 
> "A lightweight runtime CSS/JavaScript file minification, **combination**, compression & management library for ASP.Net Core"

not just minification.

Also vue-loader is not a _transpiler_ really - just splits the different sections out into javascript and css. A transpiler usually converts from one language to another.

> There must be only one Source of True!

Is this some sort of tag line? I'm not sure what you're trying to say with this 😊 

> Please describe ure Use case Using Vue Files ???????????

As I've said above - it's frustrating having to depend on Node and webpack when the whole project is .NET and C#. I've been looking for a bundler/minifier which will work for .vue files as well. I was hoping this project might be it, but I guess not...

**Comment by Diaskhan** [comment]
combination is not a intepretation !
What if our OtherComponent uses another components ?
Who will tell to the minificator what kind is this component ?

_vue-loader is a loader for webpack that allows you to author Vue components in a format called Single-File Components (SFCs):_

Ure missing a point!

```
<template lang="jade">
div
  p {{ greeting }} World!
  OtherComponent
</template>

<script>
import OtherComponent from './OtherComponent.vue'
export default {
  components: {
    OtherComponent
  },
  data () {
    return {
      greeting: 'Hello'
    }
  }
}
</script>

<style lang="stylus" scoped>
p
  font-size 2em
  text-align center
</style>
```

Webpack is

**Comment by mika76** [comment]
@Diaskhan 

>combination is not a intepretation !

I never said it was, I just said that this library does not say it is ONLY for minification.

>What if our OtherComponent uses another components ?

Just off the top of my head each .vue file could convert to a single .js file and imports should work fine in any ES6 compatible browser. (https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Statements/import)

I agree that the scope of the project could be larger or smaller, but nothing says that *everything* that vue-loader supports has to be supported. For example only general html and css could be supported. It would still be a huge win, at least for me.

But hey, it was just a question and idea - I was hoping for something and it didn't pan out and the project owner has stated his decision. I'm ok with that 👍
