### ISSUE TITLE
Does the bundling also work with common index.html files?

### ISSUE THREAD

**Issue by LisaTatum** [Shazwazza/Smidge#69]
Hello Shannon,

finally a way to programatically bundle my js/css files in asp.net 2.0 !!!

But... does this nuget also work with a common index.**html** (not razor ) file?

**Comment by LisaTatum** [comment]
ok answer is NO: 

@await Smidge.CssHereAsync()
@await Smidge.JsHereAsync()
@await Smidge.JsHereAsync("test-bundle-1")
@await Smidge.JsHereAsync("test-bundle-2")

that only works with razor files...

**Comment by Shazwazza** [comment]
Hi,

html files don't execute on the server side so that will not work, razor works because things like `@await Smidge.CssHereAsync()` need to be executed by the server.
