### ISSUE TITLE
Is it possible to programtically order bundle files before pre-processing?

### ISSUE THREAD

**Issue by mrvelic** [Shazwazza/Smidge#7]
Is it possible to order the files of a bundle programatically before they are pre-processed?
We have our bundles currently set up with globbing paths using Cassette (which then uses the intellisense reference to order the files inside the bundle).

**Comment by Shazwazza** [comment]
Yup it should be, i just didn't get around to a few of those features yet (oops forgot!): https://github.com/Shazwazza/Smidge/blob/master/src/Smidge/Models/IWebFile.cs#L12

**Comment by Shazwazza** [comment]
I'll also allow for programmatic ordering before they are processed

**Comment by Shazwazza** [comment]
Hi, I've added this functionality in this rev: c06d98e78ac49c7c036105a431f4212ae9db8c4f

So now you can supply an `Order` property to any `IWebFile`, the default is zero and it cannot be less than zero. If you assign an `Order` then it will be taken into account before the collection of files is processed.

For a more dynamic approach when using bundles, you can assign a callback. So you bundle definition could look something like:

    bundles.Create("test-bundle-1",
        new JavaScriptFile("~/Js/Bundle1/a1.js"),
        new JavaScriptFile("~/Js/Bundle1/a2.js"))
        .OnOrdering(collection =>
        {
            //return some custom ordering
            return collection.OrderBy(x => x.FilePath);
        });

Let me know if that suits your needs and i'll publish a new version and update the docs too.

**Comment by Shazwazza** [comment]
Hi, just wanted to check if the above solves your issue so I can close this one (and release a new version)

**Comment by mrvelic** [comment]
Hi,

Sorry about that! I remember reading through it and discussing with co-workers about it but I totally forgot to actually write up a reply.
As far as I can tell it looks like it would do the job :) We are a bit off actually migrating the software to a new bundler (it's for when we switch to "core").

Feel free to release if you're happy; When we actually get a chance to do some real proper testing we'll let you know if anything comes up.

Thanks again!

**Comment by Shazwazza** [comment]
Ok great, I'll close the issue for now and ship a new version. Thanks for the feedback!
