### ISSUE TITLE
file not found execption when js or css file are not inside wwwroot folders.

### ISSUE THREAD

**Issue by bakamaru** [Shazwazza/Smidge#77]
I'm trying to bundling from theme folders which are served as static file contents but Smidge always looking files from inside wwwroot folder.
Is there any configuration for that ?how can i resolve this.

**Comment by Shazwazza** [comment]
Main problem is that Smidge was created long before great things like file provider abstractions were made, so right now Smidge relies on the physical file system APIs and currently only knows about the wwwroot as the root folder (IIRC). 

What we need to do is update Smidge to use the file provider abstractions (i.e. https://docs.microsoft.com/en-us/aspnet/core/fundamentals/file-providers)  and then the sky is the limit and we can get this one done with globbing patterns https://github.com/Shazwazza/Smidge/issues/47

**Comment by Shazwazza** [comment]
It does look like you might be able to work around this for now however, in the `AddSmidge` method, there is an optional parameter for `IFileProvider fileProvider` (so we do actually use the abstractions ! sort of ;) 

By default if this is null it will use `IHostingEnvironment.WebRootFileProvider` but you could pass in something different. It might mean that the paths you use to create your bundles might need to change slightly though.

**Comment by bakamaru** [comment]
Thanks @Shazwazza , Just made fileprovider and file info and is working as expected.

**Comment by vincentparrett** [comment]
I am using the fileprovider to map files, however when in debug mode, it doesn't render the correct links.

My fileprovider root is "content", and in production mode this works great, however in debug mode it renders the links as though they were in the wwwroot folder., ie /js/xxx or /css/xxxx

I found I had to tell asp.net core to use "content" as my webroot 
````
.UseContentRoot(Path.GetDirectoryName(typeof(Startup).Assembly.Location))
.UseWebRoot("content")
````
Not ideal, I would rather have wwwroot and content  but it works ok this way, I can live with that.

**Comment by Shazwazza** [comment]
In an v4, you can supply a RequestPath to any JavaScript or CssFile which also allows for having various additional static file options.

**Comment by markadrake** [comment]
@Shazwazza I noticed the following line results in an error.

https://github.com/Shazwazza/Smidge/blame/eb018d4d350112b61e7c73e0942da1edd7a551eb/src/Smidge.Web/Startup.cs#L197

Should this be removed? If not, should we create `test10.js`?

All the best,

**Comment by Shazwazza** [comment]
I'll check it out, must be for a test I didn't commit
