### ISSUE TITLE
Uniquely included files

### ISSUE THREAD

**Issue by Kurira** [Shazwazza/Smidge#79]
Now, if I want to include `Scripts/jquery.js` first (because other files depend on it) and then include everything else `Scripts.*js`, smidge actually includes jquery file two times.

Would be nice if the script path list was a hash set.

Also maybe there is a way to use patterns for file names? I could split jquery dependent files to `jquery.lib.js`, `jquery.lib2.js` and so on, but `Scripts/jquery.*.js` doesn't work now.

**Comment by Shazwazza** [comment]
Proper globbing patterns is this issue https://github.com/Shazwazza/Smidge/issues/47 

Will need to look at the implementation for distinct files, should be fine.

**Comment by Shazwazza** [comment]
Have pushed a fix for this, duplicate files should no longer be an issue
