### ISSUE TITLE
Using different script types

### ISSUE THREAD

**Issue by eByte23** [Shazwazza/Smidge#8]
Hi,

Does Smidge allow for setting script types when using code defined script tags in razor?

For example using client side render react for example 
```
  bundles.Create("react-bundle-1", //bundle name
            new JavaScriptFile("~/Js/Bundle1/a1.jsx").ScriptType("text/babel"),
            new JavaScriptFile("~/Js/Bundle1/a2.jsx"));
```
then in razor
```
@await Smidge.JsHereAsync("test-bundle-1")
```

this would generate
```
<environment names="Development">
    <script src="react-bundle-1" type="text/babel" debug="true"></script>
</environment>
<environment names="Staging,Production">
       <script src="react-bundle-1" type="text/babel"></script>
</environment>
```

**Comment by Shazwazza** [comment]
Hi, the easiest way to set this is to use the tag helpers (see docs: https://github.com/Shazwazza/Smidge#rendering)

So you can just specify:

<script src="my-awesome-js-bundle" type="text/babel"></script> 

The docs also list using this with the environment tags too.

Please re-open if that doesn't solve your issue.
