### ISSUE TITLE
GetDefault is not thread safe

### ISSUE THREAD

**Issue by geeForceOne** [Shazwazza/Smidge#81]
I get an exemption on  `return _default[fileType];`

> System.InvalidOperationException: 'Operations that change non-concurrent collections must have exclusive access. A concurrent update was performed on this collection and corrupted its state. The collection's state is no longer correct.'

I think this method should be thread safe.

https://github.com/Shazwazza/Smidge/blob/af644c64713b2425d78949cf8e539a2fac0ff044/src/Smidge/FileProcessors/PreProcessPipelineFactory.cs#L64

**Comment by geeForceOne** [comment]
Dear @Shazwazza did you have a chance to look at the issue?

**Comment by Shazwazza** [comment]
Sorry! just been flat out lately, it's on my list to look at, should be very easy to fix with a ConcurrentDictionary, if you have time for a PR i can get that merged in ?

**Comment by geeForceOne** [comment]
Don't be sorry for that. I guess that you are doing it probably on your free time. Glad to help with a PR. I'm also bit busy at work, but I should be able to do it in the next 2-3 weeks. Thanks for your support. Giuseppe

**Comment by Shazwazza** [comment]
Sure thing, i'll message back here if i get make some time sooner, thanks!

**Comment by Shazwazza** [comment]
Have pushed a fix (https://github.com/Shazwazza/Smidge/commit/f0ea7b03edf8f479a6eb1fd18d3c7fc84c6c2df1), will try to fix a couple other small bugs now and get a 3.0.2 released today.

**Comment by geeForceOne** [comment]
Thank you so much. If I find another issue i will try to fix it myself in PR.

**Comment by benaadams** [comment]
Added an issue to corefx so its easier to find in search https://github.com/dotnet/corefx/issues/31186
