### ISSUE TITLE
@Import statement in .css file is processed even though it is commented out

### ISSUE THREAD

**Issue by jimmyconnell** [Shazwazza/Smidge#82]
When running one of our websites in "PRODUCTION" mode, one of the css bundles would fail to load.   After downloading the smidge source and including into the website, we determined that the Regex search for "@Import" would discover the following statement and attempt to find the file it referenced:
/*@import "bootstrap/variables";*/

My question:   Should comments be stripped from the files before any sort of minification is attempted?

Thanks.

**Comment by Shazwazza** [comment]
Yup will need to update the regex on this one (sorry for the huge delay!)
