### ISSUE TITLE
Unbundled files are not served correctly when in production mode

### ISSUE THREAD

**Issue by slorion** [Shazwazza/Smidge#83]
In the provided SubFolder example, `test3.js` and `test4.js` should appear in `#jsOutput`, but they do not because the server returns an empty response for this dynamic bundle.

I traced the cause down to `SmidgeController.Composite` function, when `filePaths` is initialized, the computed file paths do not use `file.ParsePath.Version`, which make them point to non-existing files in `{CurrentCacheFolder}\{filePath + file.extension}` instead of `{CurrentCacheFolder}\file.ParsePath.Version\{filePath + file.extension}`.

I will submit a PR with a fix, though I am not sure if this is the right way to correct the problem. It does solve the issue on my end.

**Comment by Shazwazza** [comment]
Thanks for the report! If you can submit a PR that'd be great, it will give me a good idea of the issue and if it solves your prob, then it's most likely a good fix :)

**Comment by slorion** [comment]
Thanks! I created the PR, let me know if it's ok.

**Comment by Shazwazza** [comment]
Sorry for the delay! Works perfectly, i'll get a new version out asap. Thanks again :)
