### ISSUE TITLE
Arrow functions break with Smidge Nuglify

### ISSUE THREAD

**Issue by sathiathirumal** [Shazwazza/Smidge#86]
I get this error when Nuglify encounters an arrow function ( => ) in javascript it's trying to uglify. 

I have tried to specify the script version as ES6 and it still fails.
```

            var codeSettings = new NUglify.JavaScript.CodeSettings();
            codeSettings.ScriptVersion = NUglify.JavaScript.ScriptVersion.EcmaScript6;
            NuglifySettings ns = new NuglifySettings(new NuglifyCodeSettings(codeSettings), new NUglify.Css.CssSettings());
            services.AddSmidgeNuglify(ns);
```

### **Error**
InvalidOperationException: Stack empty.

System.ThrowHelper.ThrowInvalidOperationException(ExceptionResource resource)
System.Collections.Generic.Stack.Pop()
NUglify.JavaScript.Visitors.OutputVisitor.Visit(FunctionObject node)
NUglify.JavaScript.Syntax.FunctionObject.Accept(IVisitor visitor)
NUglify.JavaScript.Visitors.OutputVisitor.AcceptNodeWithParens(AstNode node, bool needsParens)
NUglify.JavaScript.Visitors.OutputVisitor.Visit(ObjectLiteralProperty node)
NUglify.JavaScript.Syntax.ObjectLiteralProperty.Accept(IVisitor visitor)
NUglify.JavaScript.Visitors.OutputVisitor.Visit(AstNodeList node)
NUglify.JavaScript.Syntax.AstNodeList.Accept(IVisitor visitor)
NUglify.JavaScript.Visitors.OutputVisitor.Visit(ObjectLiteral node)
NUglify.JavaScript.Syntax.ObjectLiteral.Accept(IVisitor visitor)
NUglify.JavaScript.Visitors.OutputVisitor.AcceptNodeWithParens(AstNode node, bool needsParens)
NUglify.JavaScript.Visitors.OutputVisitor.Visit(CallExpression node)
NUglify.JavaScript.Syntax.CallExpression.Accept(IVisitor visitor)
NUglify.JavaScript.Visitors.OutputVisitor.Visit(BlockStatement node)
NUglify.JavaScript.Syntax.BlockStatement.Accept(IVisitor visitor)
NUglify.JavaScript.Visitors.OutputVisitor.OutputFunctionArgsAndBody(FunctionObject node)
NUglify.JavaScript.Visitors.OutputVisitor.Visit(FunctionObject node)
NUglify.JavaScript.Syntax.FunctionObject.Accept(IVisitor visitor)
NUglify.JavaScript.Visitors.OutputVisitor.Visit(BlockStatement node)
NUglify.JavaScript.Syntax.BlockStatement.Accept(IVisitor visitor)
NUglify.JavaScript.Visitors.OutputVisitor.Apply(TextWriter writer, AstNode node, CodeSettings settings)
NUglify.Uglify.Js(string source, string fileName, CodeSettings codeSettings)
Smidge.Nuglify.NuglifyJs.ProcessAsync(FileProcessContext fileProcessContext, PreProcessorDelegate next)
Smidge.FileProcessors.PreProcessPipeline+<ProcessNext>d__5.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Smidge.FileProcessors.PreProcessPipeline+<ProcessAsync>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Smidge.FileProcessors.PreProcessManager+<ProcessFileImpl>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Smidge.FileProcessors.PreProcessManager+<ProcessFile>d__6.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Smidge.FileProcessors.PreProcessManager+<ProcessAndCacheFileAsync>d__5.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Smidge.Controllers.SmidgeController+<Bundle>d__7.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
lambda_method(Closure , object )
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeActionMethodAsync>d__12.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeNextActionFilterAsync>d__10.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Rethrow(ActionExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ControllerActionInvoker+<InvokeInnerFilterAsync>d__14.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeNextResourceFilter>d__22.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Rethrow(ResourceExecutedContext context)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker.Next(ref State next, ref Scope scope, ref object state, ref bool isCompleted)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeFilterPipelineAsync>d__17.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Mvc.Internal.ResourceInvoker+<InvokeAsync>d__15.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Builder.RouterMiddleware+<Invoke>d__4.MoveNext()
System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware+<Invoke>d__7.MoveNext()

**Comment by Shazwazza** [comment]
Hi sorry I am unable to help with this one, Nuglify isn't my project so not much i can do about it's internal processing.
