### ISSUE TITLE
Bundles with .less files return empty response

### ISSUE THREAD

**Issue by gabrielsadaka** [Shazwazza/Smidge#87]
The PreProcessor used to compile the .less stylesheets is below:

```
public class DotlessPreProcessor : IPreProcessor
{
    private readonly IHostingEnvironment _hostingEnvironment;

    public DotlessPreProcessor(IHostingEnvironment hostingEnvironment)
    {
        _hostingEnvironment = hostingEnvironment;
    }

    public async Task ProcessAsync(FileProcessContext fileProcessContext, PreProcessorDelegate next)
    {
        if (Path.GetExtension(fileProcessContext.WebFile.FilePath) == ".less")
        {
            var result = new AspNetCoreEngineFactory().Parse(fileProcessContext.FileContent, _hostingEnvironment);
            fileProcessContext.Update(result);
        }

        await next(fileProcessContext);
    }
}
```

The bundle is defined with:

```
bundles.Create("Content-css", WebFileType.Css, CssPath + "/page.less");
```

Then loaded with: 

```
await _smidgeHelper.CssHereAsync("Content-css", false);
```

The final result is a 200 with empty content. 

It successfully generates the `.less` files in the cache but in the gzip folder the bundle files are 0kb.

**Comment by gabrielsadaka** [comment]
The underlying issue is that the pre processors don't allow the file name to be changed so once we used DotLess to compile the less to css we were unable to rewrite the file name in the bundle to .css. If we are able to change the file name in the pre processor than Smidge would not need to know anything about .less files which it definitely shouldn't anyway.

**Comment by Shazwazza** [comment]
Your PR was actually the right fix. Smidge currently relies on file caches and being named right, in fact there are only 2 places in the codebase that use the _fileSystemHelper.GetCacheFilePath and one uses the file extension (correct) and the other used the bundle extensions (incorrect as you mentioned). 

I've pushed a fix, hopefully i'll get something shipped soon.

**Comment by gabrielsadaka** [comment]
That's great, thanks for having a look at it.
