### ISSUE TITLE
.net core 3.0 preview 4 breaks smidge

### ISSUE THREAD

**Issue by vincentparrett** [Shazwazza/Smidge#89]
It appears as though .net core 3.0 preview 4 breaks smidge - the SmidgeLinkTagHelper and SmidgeScriptTagHelper are never called. I have tried to debug this but so far have not been able to figure out the cause.  Downgraded to preview 3 and it works again. 

I suspect there will be issues with the controller too, as routing has changed to use Enpoint routing.

**Comment by vincentparrett** [comment]
It seems linking to 

````xml
<PackageReference Include="Microsoft.AspNetCore.Mvc" Version="2.0.0" />
````
is the problem. With this, no matter what you do, tag helpers are not called. This seems to be a breaking change in aspnetcore, although so far I have found no reference to it. If I change this reference to 

````xml
  <PackageReference Include="Microsoft.AspNetCore.Razor" Version="2.1.0" />
````
Then it works. Sadly taghelpers don't appear to be in version 2.0.x of this assembly. 

This is problematic, because it will break support for asp.net core 2.0 and aspnetcore on the .net framework (although this has been dropped on aspnetcore 3.0).
 
Reported issue  [#9766](https://github.com/aspnet/AspNetCore/issues/9766) in the aspnetcore project.

**Comment by Shazwazza** [comment]
Thanks for reporting! I'm pretty swamped at the moment but will get to this eventually (hopefully soon). Feel free to submit any PRs to assist if you have time! Thanks :)

**Comment by vincentparrett** [comment]
I decided to have another go at this today, and after banging my head for a few hours I finally have it working. Just tidying up and will push the changes shortly.

**Comment by Shazwazza** [comment]
whoohoo! I'll take a look shortly, thanks :)

**Comment by Shazwazza** [comment]
Will close this as this all seems to work in https://github.com/Shazwazza/Smidge/pull/90
