### ISSUE TITLE
Inline JS

### ISSUE THREAD

**Issue by EnterpriseWide** [Shazwazza/Smidge#93]
An inline Javascript require type statement that allows for javascript to be added per view and not just references to javascript files would be useful.

**Comment by Shazwazza** [comment]
Hi sorry for the delay and thanks for the request. I had thought of this feature in the old https://github.com/shazwazza/clientdependency project but it just seemed simpler in the end to just create a JS file. I don't plan on implementing this in Smidge, however if you have time and would like to give it a try then please by all means give it a go! :)
