### ISSUE TITLE
Esbuild

### ISSUE THREAD

**Issue by Diaskhan** [Shazwazza/Smidge#97]
Have u seen esbuild ? 
https://github.com/evanw/esbuild

Few moth ago Ewan present vite !
Vite is dev server for vuejs developing with hmr!

U could borrow some ideas from vite and esbuild !

**Comment by Shazwazza** [comment]
Thanks for the info, that library is written in Go so can't really use it in any way. Smidge is a flexible bundler/minifier and currently the minifying tools are either the built in JsMin or Nuglify, there's not many other option out there for c# at the moment and Smidge doesn't aim at creating a new minifier engine.
